spring: 
    profiles: 
        active:
           - dev
---
server:
  port: 8001

spring:
  profiles: dev
  application:
    name: microservicecloud-config-dept-client   #为这个服务取名，非常重要！！！！！
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: dept8001
    prefer-ip-address: true
---
server:
  port: 8001

spring:
  profiles: test
  application:
    name: microservicecloud-config-dept-client   #为这个服务取名，非常重要！！！！！
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: dept8001
    prefer-ip-address: true